blog/api/urls.py
from django.urls import path

from blog.api.views import (
    api_blog_detail_view,
    api_blog_create_view,
    api_blog_delete_view,
    api_blog_update_view,
)

app_name = 'blog'
urlpatterns = [
    path('<slug>/',api_blog_detail_view,name="detail"),
    path('<slug>/update',api_blog_update_view,name="update"),
    path('create',api_blog_create_view,name="create"),
    path('<slug>/delete',api_blog_delete_view,name="delete"),
]

blog/urls.py
from django.urls import path
from blog.views import (
    create_blog_view,
    detail_blog_view,
    edit_blog_view,
    like_post_view,
)

app_name = 'blog'

urlpatterns = [
    path('create',create_blog_view,name='create'),
    path('<slug>',detail_blog_view,name='detail'),
    path('<slug>/edit',edit_blog_view,name='edit'),
    path('<slug>/like',like_post_view,name='like'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from personal.views import (
    home_screen_view,
)
from account.views import (
    registration_view,
    logout_view,
    login_view,
    account_view,
    must_authenticate_view
)
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',home_screen_view,name='home'),
    path('register/',registration_view,name='register'),
    path('logout/',logout_view,name="logout"),
    path('login/',login_view,name='login'),
    path('account/',account_view,name="account"),
    path('must_authenticate',must_authenticate_view,name='must_authenticate'),

    path('blog/',include('blog.urls','blog')),

    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'), 
        name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'), 
        name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
     name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
     name='password_reset_complete'),

    #REST FRAMEWORK
    path('api/blog/',include('blog.api.urls','blog_api')),
    path('api/account/',include('account.api.urls','account_api'))

    

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
    

blog/models.py
from django.db import models
from django.db.models.signals import pre_save, post_delete
from django.utils.text import slugify
from django.conf import settings
from django.dispatch import receiver
# Create your models here.

def upload_location(instance,filename):
    file_path = 'blog/{author_id}/{title}-{filename}'.format(
        author_id=str(instance.author.id),
        title = str(instance.title),
        filename = filename,    
    )
    return file_path

class BlogPost(models.Model):
    objects                = models.Manager()
    title                  = models.CharField(max_length=50,null=False,blank=False)
    body                   = models.TextField(max_length=3000,null=False,blank=False)
    image                  = models.ImageField(upload_to=upload_location,null=False,blank=False)
    date_published         = models.DateTimeField(auto_now_add=True,verbose_name='date_published')
    date_updated           = models.DateTimeField(auto_now_add=True,verbose_name='date_updated')
    author                 = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    slug                   = models.SlugField(blank=True,unique=True)
    likes                  = models.IntegerField(default=0)
    views                  = models.IntegerField(default=0)

    def __str__(self):
        return self.title

@receiver(post_delete,sender=BlogPost)
def submission_delete(sender, instance,**kwargs):
    instance.image.delete(False)

def pre_save_blog_post_reciever(sender,instance,*args,**kwargs):
    if not instance.slug:
        instance.slug = slugify(instance.author.username+"-"+instance.title)

pre_save.connect(pre_save_blog_post_reciever,sender=BlogPost)
   
class Like(models.Model):
    objects         = models.Manager()
    user            = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    post            = models.ForeignKey(BlogPost,on_delete=models.CASCADE)

blog/forms.py
from django import forms
from blog.models import BlogPost

class CreateBlogPostForm(forms.ModelForm):

    class Meta:
        model = BlogPost
        fields = ['title','body','image']

class UpdateBlogPostForm(forms.ModelForm):

    class Meta:
        model = BlogPost
        fields = ['title','body','image']

    def save(self,commit=True):
        blog_post = self.instance
        blog_post.title = self.cleaned_data['title']
        blog_post.body = self.cleaned_data['body']

        if self.cleaned_data['image']:
            blog_post.image = self.cleaned_data['image']
        
        if commit:
            blog_post.save()
        
        return blog_post  

blog/api/views.py
from rest_framework import status
from rest_framework.decorators import api_view, permission_classes
from rest_framework.response import Response
from rest_framework.permissions import IsAuthenticated

from account.models import Account
from blog.models import BlogPost
from blog.api.serializers import BlogPostSerializer

#API DETAIL VIEW
@api_view(['GET', ])
@permission_classes((IsAuthenticated))
def api_blog_detail_view(request,slug):
    try:
        blogpost = BlogPost.objects.get(slug=slug)
    except:
        return Response(status=status.HTTP_404_NOT_FOUND)
    serializer = BlogPostSerializer(blogpost)
    return Response(serializer.data)

#API UPDATE VIEW
@api_view(["PUT",])
@permission_classes((IsAuthenticated))
def api_blog_update_view(request,slug):
    try:
        blogpost = BlogPost.objects.get(slug=slug)
    except:
        return Response(status = status.HTTP_404_NOT_FOUND)
    user = request.user
    if blogpost.author != user:
        return Response({'response':'you donot have permission to edit this post'})
    data = {}
    serializer = BlogPostSerializer(blogpost)
    if request.method=="PUT":
        if serializer.is_valid():
            serializer.save()
            data["success"] = "your update was successful:)"
            return Response(data=data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

#API DELETE VIEW
@api_view(['DELETE',])
@permission_classes((IsAuthenticated))
def api_blog_delete_view(request,slug):
    try:
        blogpost = BlogPost.objects.get(slug=slug)
    except:
        return Response(status=status.HTTP_404_NOT_FOUND)
    user = request.user
    if blogpost.author != user:
        return Response({'response':'you donot have permission to edit this post'})
    data = {}
    operation = blogpost.delete()
    if operation :
        data["success"] = "deletion was successful:)"
    else :
        data["failure"] = "deletion was unsuccessful:("
    return Response(data=data)

@api_view(['POST',])
@permission_classes((IsAuthenticated))
def api_blog_create_view(request):
    account = request.user

    blogpost = BlogPost(author=account)
    serializer = BlogPostSerializer(blogpost,data=request.data)
    data = {}
    if serializer.is_valid():
        serializer.save()
        return Response(serializer.data,status=status.HTTP_201_CREATED)
    return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST )

blog/views.py
from django.shortcuts import render,redirect, get_object_or_404, HttpResponse
from blog.models import BlogPost, Like
from blog.forms import CreateBlogPostForm, UpdateBlogPostForm
from account.models import Account
from django.db.models import Q
import inspect
# Create your views here.
def create_blog_view(request):
    context = {}
    user = request.user
    if not user.is_authenticated:
        return redirect('must_authenticate')
    
    form = CreateBlogPostForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        obj = form.save(commit=False)
        author = Account.objects.filter(email=user.email).first()
        obj.author = author
        obj.save()
        form = CreateBlogPostForm()
    context['form'] = form

    return render(request,'blog/create_blog.html',context)

def detail_blog_view(request,slug):
    context = {}
    blog_post = get_object_or_404(BlogPost,slug=slug)
    context["blog_post"] = blog_post
    if request.user != blog_post.author and str(inspect.stack()[2][3])!="like_post_view":
        blog_post.views+=1
    blog_post.save()
    return render(request,'blog/detail_blog.html',context)

def edit_blog_view(request,slug):
    context = {}
    if not request.user.is_authenticated:
        return redirect('must_authenticate')

    blog_post = get_object_or_404(BlogPost,slug=slug)
    if blog_post.author != request.user:
        return HttpResponse("You are not the author for this post")
    if request.POST:
        form = UpdateBlogPostForm(request.POST or None, request.FILES or None, instance=blog_post)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.save()
            context["success_message"] = "Blog Updated!"
            blog_post = obj

    form = UpdateBlogPostForm(
        initial={
            'title' : blog_post.title,
            'body' : blog_post.body,
            'image' : blog_post.image,
        }
    )
    context["update_form"] = form
    return render(request,'blog/edit_blog.html',context)

def like_post_view(request,slug):
    if not request.user.is_authenticated:
        return redirect('must_authenticate')
    post = get_object_or_404(BlogPost,slug=slug)
    if request.user == post.author:
        return HttpResponse("Don't try to be cheeky. You cannot like your own post")

    new_like, created = Like.objects.get_or_create(user=request.user,post=post)
    if not created:
        return detail_blog_view(request,slug)
    else:
        post.likes+=1
        post.save()
        return detail_blog_view(request,slug)

blog/templates/blog/create_blog.html
{% extends 'base.html' %}

{% block content %}

<style type="text/css">
    .create-form {
          width: 100%;
          max-width: 100%;
          padding: 15px;
          margin: auto;
        }
  
        .submit-button{
            max-width: 200px;
        }
  </style>
  
  <div class="container">
      <div class="row">
          <div class="col-lg-7 offset-lg-1">
              <form class="create-form" method="post" enctype="multipart/form-data">{% csrf_token %}
  
                  <!-- title -->
                  <div class="form-group">
                      <label for="id_title">Title</label>
                      <input class="form-control" type="text" name="title" id="id_title" placeholder="Title" required autofocus>
                  </div>
  
                  <!-- Body -->
                  <div class="form-group">
                      <label for="id_body">Content</label>
                      <textarea class="form-control" rows="10" type="text" name="body" id="id_body" placeholder="This blog is about..." required></textarea>
                  </div>
  
                  <!-- Image -->
                  <div class="form-group">
                      <label for="id_image">Image</label>
                      <input  type="file" name="image" id="id_image" accept="image/*" required>
                  </div>
  
                  <!-- Submit btn -->
                  <button class="submit-button btn btn-lg btn-primary btn-block" type="submit">POST</button>
              </form>	
          </div>
      </div>
  </div>
  

{% endblock content %}

blog/templates/blog/detail_blog.html
{% extends 'base.html' %}
{% block content %}



<div>
<img src="{{ blog_post.image.url }}" width="20" height="20"><h3>{{ blog_post.title }}</h3>
{% if request.user == blog_post.author %}
<a href="{% url 'blog:edit' blog_post.slug %}">Update Post</a>
{% endif %}
<h5>By {{ blog_post.author }} | {{ blog_post.date_published }} </h5>
<p>{{ blog_post.body|safe|linebreaks }}</p>
<br>
<p>Views: {{ blog_post.views }}</p>
<br>
<a href="{% url 'blog:like' blog_post.slug %}">Like</a>
<p>Likes: {{ blog_post.likes }}</p>
</div>



{% endblock content %}

blog/templates/blog/edit_blog.html
{% extends 'base.html' %}
{% block content %}

<h2>Update your Blog</h2>
<form method="POST">
    {% csrf_token %}
    {% for field in update_form %}
    <p>
        {{ field.label }}
        {{ field }}
        {% if field.help_text %}
        <small style="color: rgb(148, 147, 147);">{{ field.help_text }}</small>
        {% endif %}
        {% for errors in field.errors %}
        <small style="color:red;">{{ error }}</small>
        {% endfor %}
    </p>
    {% endfor %}
    {% if update_form.non_field_errors %}
        <small style="color: red;">{{ update_form.non_field_errors }}</small>
    {% endif %}
    {% if success_message %}
    <p style="color: green;">{{ success_message }}</p>
    {% endif %}
    <button type="submit">Update My Blog</button>
</form>

{% endblock content %}