blog/urls.py
from django.urls import path
from blog.views import (
    create_blog_view,
    detail_blog_view,
    edit_blog_view,
    like_post_view,
)

app_name = 'blog'

urlpatterns = [
    path('create',create_blog_view,name='create'),
    path('<slug>',detail_blog_view,name='detail'),
    path('<slug>/edit',edit_blog_view,name='edit'),
    path('<slug>/like',like_post_view,name='like'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from personal.views import (
    home_screen_view,
)
from account.views import (
    registration_view,
    logout_view,
    login_view,
    account_view,
    must_authenticate_view
)
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',home_screen_view,name='home'),
    path('register/',registration_view,name='register'),
    path('logout/',logout_view,name="logout"),
    path('login/',login_view,name='login'),
    path('account/',account_view,name="account"),
    path('must_authenticate',must_authenticate_view,name='must_authenticate'),

    path('blog/',include('blog.urls','blog')),

    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'), 
        name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'), 
        name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
     name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
     name='password_reset_complete'),

    #REST FRAMEWORK
    path('api/blog/',include('blog.api.urls','blog_api')),
    path('api/account/',include('account.api.urls','account_api'))

    

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
    

personal/models.py
from django.db import models

# Create your models here.
# PRIORITY = [
#     ('L',"LOW"),
#     ('M',"MEDIUM"),
#     ('H',"HIGH"),
# ]

# class Question(models.Model):
#     title           = models.CharField(max_length=70)
#     question        = models.TextField()
#     priority        = models.CharField(max_length=1,choices=PRIORITY)

#     objects = models.Manager()

#     def __str__(self):
#         return self.title+"\n"+self.question

#     class Meta:
#         verbose_name = "The Question"
#         verbose_name_plural = "People's Questions"

personal/views.py
from django.shortcuts import render
from account.models import Account
from blog.models import BlogPost
# from personal.models import Question
# Create your views here.

def home_screen_view(request):
    context = {}
    context["accounts"] = Account.objects.all()
    all_posts = BlogPost.objects.all()
    context["all_posts"] = all_posts

    return render(request,'personal/home.html',context)

personal/templates/personal/home.html
{% extends 'base.html' %}
{% block content %}

<style type="text/css">

	@media (max-width: 768px) { 
		.right-column{
			margin-left: 0px;
		}
	}

	@media (min-width: 768px) { 
		.right-column{
			margin-left: 20px;
		}
	}

	.blog-post-container{
		margin-bottom: 20px;
		width: 100%;
	}
	.create-post-bar{
		background-color: #fff;
		margin-bottom:20px;
	}

	.left-column{
		padding:0px;
	}

	.right-column{
		padding:0px;
	}
	.lead{
		font-size: 17px;
	}
</style>


<div class="container">
    <div class="row">
        <!--Create Postbar-->
        <div class="create-post-bar d-lg-none col-lg-7 offset-lg-1">
            <a href="{% url 'blog:create' %}">Create new post</a>
        </div>
        <!--End Create Postbar-->
        <!--Blog Feed-->
        <div class="left-column col-lg-7 offset-lg-1">
			{% if all_posts %}
			<ul>
				{% for post in all_posts %}
				<li><a href="{% url 'blog:detail' post.slug %}">{{ post.title }}</a></li>
			{% endfor %}
			</ul>
			
			{% else %}
			<p>Its too lonely on the feed, pls post a blog :(</p>
			{% endif %}
        </div>
        <!--End Blog Feed-->
        <!--Create Post-->
        <div class="right-column col-lg-3 d-lg-flex d-none flex-column">
			<a href="{% url 'blog:create' %}">Create new post</a>
        </div>
        <!--End Create Post-->
    </div>
</div>


{% endblock content %}